site_name: geospatial-analysis-tools 

theme: 
  name: material 
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant

  palette:
    primary: teal 

  font:
    code: Roboto Mono

  extra_css:
    - custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences