site_name: Roger Almengor González 

plugins:
  - blogging:
      dirs: # The directories to be included
        - blog
      theme:
        name: card
        name: button
        options: # Optional
          # `true` if display the button as plain text
          # `false` or not present if display as rectangle button
          plain_button: true
          # Replacement for 'Continue Reading'
          label: Read
site_url: https://rogeralmengor.github.io/geospatial-analysis.io/

time_format: '%Y-%m-%d'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

theme: 
  name: material 
  icon:
    admonition:
      <code>: octicons/code-16 
  features:
    - content.code.copy
    - content.code.select
#    - navigation.instant

  palette:
    primary: teal 

  font:
    text: Montserrat
    code: Roboto Mono

  extra_css:
    - custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
